version: "3.3"
services:
  dev:
    container_name: nhtsa-dev
    build:
      context: ./dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - type: bind
        source: ./
        target: /workspace
    environment:
      ENV: development
